"""Mutual Funds, Index Funds, ETFs, Sovereign Debt & Gold Assets Catalog."""

INVESTMENT_ASSET_CATALOG = {
    "ASSET_FINX_NIFTY_50_INDEX_0001": {
        "asset_code": "ASSET_FINX_NIFTY_50_INDEX_0001",
        "scheme_name": "FinX Asset Management Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "FinX Asset Management",
        "nav": 11.73,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_NIFTY_NEXT_50_0002": {
        "asset_code": "ASSET_FINX_NIFTY_NEXT_50_0002",
        "scheme_name": "FinX Asset Management Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "FinX Asset Management",
        "nav": 13.46,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_MIDCAP_OPPORTUNITIES_0003": {
        "asset_code": "ASSET_FINX_MIDCAP_OPPORTUNITIES_0003",
        "scheme_name": "FinX Asset Management Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "FinX Asset Management",
        "nav": 15.19,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_SMALL_CAP_DISCOVERY_0004": {
        "asset_code": "ASSET_FINX_SMALL_CAP_DISCOVERY_0004",
        "scheme_name": "FinX Asset Management Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "FinX Asset Management",
        "nav": 16.92,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_FOCUSED_EQUITY_30_0005": {
        "asset_code": "ASSET_FINX_FOCUSED_EQUITY_30_0005",
        "scheme_name": "FinX Asset Management Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "FinX Asset Management",
        "nav": 18.65,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_HEALTHCARE_PHARMA_ETF_0006": {
        "asset_code": "ASSET_FINX_HEALTHCARE_PHARMA_ETF_0006",
        "scheme_name": "FinX Asset Management Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "FinX Asset Management",
        "nav": 20.38,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_TECHNOLOGY_AI_ETF_0007": {
        "asset_code": "ASSET_FINX_TECHNOLOGY_AI_ETF_0007",
        "scheme_name": "FinX Asset Management Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "FinX Asset Management",
        "nav": 22.11,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_BANKING_FINANCIAL_ETF_0008": {
        "asset_code": "ASSET_FINX_BANKING_FINANCIAL_ETF_0008",
        "scheme_name": "FinX Asset Management Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "FinX Asset Management",
        "nav": 23.84,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_CORPORATE_BOND_AAA_0009": {
        "asset_code": "ASSET_FINX_CORPORATE_BOND_AAA_0009",
        "scheme_name": "FinX Asset Management Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "FinX Asset Management",
        "nav": 25.57,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_SHORT_TERM_DEBT_FUND_0010": {
        "asset_code": "ASSET_FINX_SHORT_TERM_DEBT_FUND_0010",
        "scheme_name": "FinX Asset Management Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "FinX Asset Management",
        "nav": 27.3,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_OVERNIGHT_LIQUID_FUND_0011": {
        "asset_code": "ASSET_FINX_OVERNIGHT_LIQUID_FUND_0011",
        "scheme_name": "FinX Asset Management Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "FinX Asset Management",
        "nav": 29.03,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_FINX_SOVEREIGN_GOLD_BOND_0012": {
        "asset_code": "ASSET_FINX_SOVEREIGN_GOLD_BOND_0012",
        "scheme_name": "FinX Asset Management Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "FinX Asset Management",
        "nav": 30.76,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_NIFTY_50_INDEX_0013": {
        "asset_code": "ASSET_HDFC_NIFTY_50_INDEX_0013",
        "scheme_name": "HDFC Mutual Fund Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 32.49,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_NIFTY_NEXT_50_0014": {
        "asset_code": "ASSET_HDFC_NIFTY_NEXT_50_0014",
        "scheme_name": "HDFC Mutual Fund Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 34.22,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_MIDCAP_OPPORTUNITIES_0015": {
        "asset_code": "ASSET_HDFC_MIDCAP_OPPORTUNITIES_0015",
        "scheme_name": "HDFC Mutual Fund Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 35.95,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_SMALL_CAP_DISCOVERY_0016": {
        "asset_code": "ASSET_HDFC_SMALL_CAP_DISCOVERY_0016",
        "scheme_name": "HDFC Mutual Fund Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 37.68,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_FOCUSED_EQUITY_30_0017": {
        "asset_code": "ASSET_HDFC_FOCUSED_EQUITY_30_0017",
        "scheme_name": "HDFC Mutual Fund Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 39.41,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_HEALTHCARE_PHARMA_ETF_0018": {
        "asset_code": "ASSET_HDFC_HEALTHCARE_PHARMA_ETF_0018",
        "scheme_name": "HDFC Mutual Fund Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 41.14,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_TECHNOLOGY_AI_ETF_0019": {
        "asset_code": "ASSET_HDFC_TECHNOLOGY_AI_ETF_0019",
        "scheme_name": "HDFC Mutual Fund Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 42.87,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_BANKING_FINANCIAL_ETF_0020": {
        "asset_code": "ASSET_HDFC_BANKING_FINANCIAL_ETF_0020",
        "scheme_name": "HDFC Mutual Fund Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 44.6,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_CORPORATE_BOND_AAA_0021": {
        "asset_code": "ASSET_HDFC_CORPORATE_BOND_AAA_0021",
        "scheme_name": "HDFC Mutual Fund Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 46.33,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_SHORT_TERM_DEBT_FUND_0022": {
        "asset_code": "ASSET_HDFC_SHORT_TERM_DEBT_FUND_0022",
        "scheme_name": "HDFC Mutual Fund Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 48.06,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_OVERNIGHT_LIQUID_FUND_0023": {
        "asset_code": "ASSET_HDFC_OVERNIGHT_LIQUID_FUND_0023",
        "scheme_name": "HDFC Mutual Fund Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 49.79,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_HDFC_SOVEREIGN_GOLD_BOND_0024": {
        "asset_code": "ASSET_HDFC_SOVEREIGN_GOLD_BOND_0024",
        "scheme_name": "HDFC Mutual Fund Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "HDFC Mutual Fund",
        "nav": 51.52,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _NIFTY_50_INDEX_0025": {
        "asset_code": "ASSET_SBI _NIFTY_50_INDEX_0025",
        "scheme_name": "SBI Mutual Fund Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "SBI Mutual Fund",
        "nav": 53.25,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _NIFTY_NEXT_50_0026": {
        "asset_code": "ASSET_SBI _NIFTY_NEXT_50_0026",
        "scheme_name": "SBI Mutual Fund Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "SBI Mutual Fund",
        "nav": 54.98,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _MIDCAP_OPPORTUNITIES_0027": {
        "asset_code": "ASSET_SBI _MIDCAP_OPPORTUNITIES_0027",
        "scheme_name": "SBI Mutual Fund Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "SBI Mutual Fund",
        "nav": 56.71,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _SMALL_CAP_DISCOVERY_0028": {
        "asset_code": "ASSET_SBI _SMALL_CAP_DISCOVERY_0028",
        "scheme_name": "SBI Mutual Fund Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "SBI Mutual Fund",
        "nav": 58.44,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _FOCUSED_EQUITY_30_0029": {
        "asset_code": "ASSET_SBI _FOCUSED_EQUITY_30_0029",
        "scheme_name": "SBI Mutual Fund Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "SBI Mutual Fund",
        "nav": 60.17,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _HEALTHCARE_PHARMA_ETF_0030": {
        "asset_code": "ASSET_SBI _HEALTHCARE_PHARMA_ETF_0030",
        "scheme_name": "SBI Mutual Fund Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "SBI Mutual Fund",
        "nav": 61.9,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _TECHNOLOGY_AI_ETF_0031": {
        "asset_code": "ASSET_SBI _TECHNOLOGY_AI_ETF_0031",
        "scheme_name": "SBI Mutual Fund Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "SBI Mutual Fund",
        "nav": 63.63,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _BANKING_FINANCIAL_ETF_0032": {
        "asset_code": "ASSET_SBI _BANKING_FINANCIAL_ETF_0032",
        "scheme_name": "SBI Mutual Fund Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "SBI Mutual Fund",
        "nav": 65.36,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _CORPORATE_BOND_AAA_0033": {
        "asset_code": "ASSET_SBI _CORPORATE_BOND_AAA_0033",
        "scheme_name": "SBI Mutual Fund Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "SBI Mutual Fund",
        "nav": 67.09,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _SHORT_TERM_DEBT_FUND_0034": {
        "asset_code": "ASSET_SBI _SHORT_TERM_DEBT_FUND_0034",
        "scheme_name": "SBI Mutual Fund Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "SBI Mutual Fund",
        "nav": 68.82,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _OVERNIGHT_LIQUID_FUND_0035": {
        "asset_code": "ASSET_SBI _OVERNIGHT_LIQUID_FUND_0035",
        "scheme_name": "SBI Mutual Fund Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "SBI Mutual Fund",
        "nav": 70.55,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_SBI _SOVEREIGN_GOLD_BOND_0036": {
        "asset_code": "ASSET_SBI _SOVEREIGN_GOLD_BOND_0036",
        "scheme_name": "SBI Mutual Fund Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "SBI Mutual Fund",
        "nav": 72.28,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_NIFTY_50_INDEX_0037": {
        "asset_code": "ASSET_ICIC_NIFTY_50_INDEX_0037",
        "scheme_name": "ICICI Prudential AMC Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 74.01,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_NIFTY_NEXT_50_0038": {
        "asset_code": "ASSET_ICIC_NIFTY_NEXT_50_0038",
        "scheme_name": "ICICI Prudential AMC Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 75.74,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_MIDCAP_OPPORTUNITIES_0039": {
        "asset_code": "ASSET_ICIC_MIDCAP_OPPORTUNITIES_0039",
        "scheme_name": "ICICI Prudential AMC Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 77.47,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_SMALL_CAP_DISCOVERY_0040": {
        "asset_code": "ASSET_ICIC_SMALL_CAP_DISCOVERY_0040",
        "scheme_name": "ICICI Prudential AMC Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 79.2,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_FOCUSED_EQUITY_30_0041": {
        "asset_code": "ASSET_ICIC_FOCUSED_EQUITY_30_0041",
        "scheme_name": "ICICI Prudential AMC Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 80.93,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_HEALTHCARE_PHARMA_ETF_0042": {
        "asset_code": "ASSET_ICIC_HEALTHCARE_PHARMA_ETF_0042",
        "scheme_name": "ICICI Prudential AMC Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 82.66,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_TECHNOLOGY_AI_ETF_0043": {
        "asset_code": "ASSET_ICIC_TECHNOLOGY_AI_ETF_0043",
        "scheme_name": "ICICI Prudential AMC Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 84.39,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_BANKING_FINANCIAL_ETF_0044": {
        "asset_code": "ASSET_ICIC_BANKING_FINANCIAL_ETF_0044",
        "scheme_name": "ICICI Prudential AMC Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 86.12,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_CORPORATE_BOND_AAA_0045": {
        "asset_code": "ASSET_ICIC_CORPORATE_BOND_AAA_0045",
        "scheme_name": "ICICI Prudential AMC Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 87.85,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_SHORT_TERM_DEBT_FUND_0046": {
        "asset_code": "ASSET_ICIC_SHORT_TERM_DEBT_FUND_0046",
        "scheme_name": "ICICI Prudential AMC Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 89.58,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_OVERNIGHT_LIQUID_FUND_0047": {
        "asset_code": "ASSET_ICIC_OVERNIGHT_LIQUID_FUND_0047",
        "scheme_name": "ICICI Prudential AMC Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 91.31,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_ICIC_SOVEREIGN_GOLD_BOND_0048": {
        "asset_code": "ASSET_ICIC_SOVEREIGN_GOLD_BOND_0048",
        "scheme_name": "ICICI Prudential AMC Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "ICICI Prudential AMC",
        "nav": 93.04,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_NIFTY_50_INDEX_0049": {
        "asset_code": "ASSET_NIPP_NIFTY_50_INDEX_0049",
        "scheme_name": "Nippon India MF Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "Nippon India MF",
        "nav": 94.77,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_NIFTY_NEXT_50_0050": {
        "asset_code": "ASSET_NIPP_NIFTY_NEXT_50_0050",
        "scheme_name": "Nippon India MF Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "Nippon India MF",
        "nav": 96.5,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_MIDCAP_OPPORTUNITIES_0051": {
        "asset_code": "ASSET_NIPP_MIDCAP_OPPORTUNITIES_0051",
        "scheme_name": "Nippon India MF Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "Nippon India MF",
        "nav": 98.23,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_SMALL_CAP_DISCOVERY_0052": {
        "asset_code": "ASSET_NIPP_SMALL_CAP_DISCOVERY_0052",
        "scheme_name": "Nippon India MF Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "Nippon India MF",
        "nav": 99.96,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_FOCUSED_EQUITY_30_0053": {
        "asset_code": "ASSET_NIPP_FOCUSED_EQUITY_30_0053",
        "scheme_name": "Nippon India MF Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "Nippon India MF",
        "nav": 101.69,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_HEALTHCARE_PHARMA_ETF_0054": {
        "asset_code": "ASSET_NIPP_HEALTHCARE_PHARMA_ETF_0054",
        "scheme_name": "Nippon India MF Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "Nippon India MF",
        "nav": 103.42,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_TECHNOLOGY_AI_ETF_0055": {
        "asset_code": "ASSET_NIPP_TECHNOLOGY_AI_ETF_0055",
        "scheme_name": "Nippon India MF Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "Nippon India MF",
        "nav": 105.15,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_BANKING_FINANCIAL_ETF_0056": {
        "asset_code": "ASSET_NIPP_BANKING_FINANCIAL_ETF_0056",
        "scheme_name": "Nippon India MF Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "Nippon India MF",
        "nav": 106.88,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_CORPORATE_BOND_AAA_0057": {
        "asset_code": "ASSET_NIPP_CORPORATE_BOND_AAA_0057",
        "scheme_name": "Nippon India MF Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "Nippon India MF",
        "nav": 108.61,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_SHORT_TERM_DEBT_FUND_0058": {
        "asset_code": "ASSET_NIPP_SHORT_TERM_DEBT_FUND_0058",
        "scheme_name": "Nippon India MF Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "Nippon India MF",
        "nav": 110.34,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_OVERNIGHT_LIQUID_FUND_0059": {
        "asset_code": "ASSET_NIPP_OVERNIGHT_LIQUID_FUND_0059",
        "scheme_name": "Nippon India MF Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "Nippon India MF",
        "nav": 112.07,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_NIPP_SOVEREIGN_GOLD_BOND_0060": {
        "asset_code": "ASSET_NIPP_SOVEREIGN_GOLD_BOND_0060",
        "scheme_name": "Nippon India MF Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "Nippon India MF",
        "nav": 113.8,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_NIFTY_50_INDEX_0061": {
        "asset_code": "ASSET_KOTA_NIFTY_50_INDEX_0061",
        "scheme_name": "Kotak Mahindra AMC Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 115.53,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_NIFTY_NEXT_50_0062": {
        "asset_code": "ASSET_KOTA_NIFTY_NEXT_50_0062",
        "scheme_name": "Kotak Mahindra AMC Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 117.26,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_MIDCAP_OPPORTUNITIES_0063": {
        "asset_code": "ASSET_KOTA_MIDCAP_OPPORTUNITIES_0063",
        "scheme_name": "Kotak Mahindra AMC Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 118.99,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_SMALL_CAP_DISCOVERY_0064": {
        "asset_code": "ASSET_KOTA_SMALL_CAP_DISCOVERY_0064",
        "scheme_name": "Kotak Mahindra AMC Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 120.72,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_FOCUSED_EQUITY_30_0065": {
        "asset_code": "ASSET_KOTA_FOCUSED_EQUITY_30_0065",
        "scheme_name": "Kotak Mahindra AMC Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 122.45,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_HEALTHCARE_PHARMA_ETF_0066": {
        "asset_code": "ASSET_KOTA_HEALTHCARE_PHARMA_ETF_0066",
        "scheme_name": "Kotak Mahindra AMC Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 124.18,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_TECHNOLOGY_AI_ETF_0067": {
        "asset_code": "ASSET_KOTA_TECHNOLOGY_AI_ETF_0067",
        "scheme_name": "Kotak Mahindra AMC Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 125.91,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_BANKING_FINANCIAL_ETF_0068": {
        "asset_code": "ASSET_KOTA_BANKING_FINANCIAL_ETF_0068",
        "scheme_name": "Kotak Mahindra AMC Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 127.64,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_CORPORATE_BOND_AAA_0069": {
        "asset_code": "ASSET_KOTA_CORPORATE_BOND_AAA_0069",
        "scheme_name": "Kotak Mahindra AMC Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 129.37,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_SHORT_TERM_DEBT_FUND_0070": {
        "asset_code": "ASSET_KOTA_SHORT_TERM_DEBT_FUND_0070",
        "scheme_name": "Kotak Mahindra AMC Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 131.1,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_OVERNIGHT_LIQUID_FUND_0071": {
        "asset_code": "ASSET_KOTA_OVERNIGHT_LIQUID_FUND_0071",
        "scheme_name": "Kotak Mahindra AMC Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 132.83,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_KOTA_SOVEREIGN_GOLD_BOND_0072": {
        "asset_code": "ASSET_KOTA_SOVEREIGN_GOLD_BOND_0072",
        "scheme_name": "Kotak Mahindra AMC Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "Kotak Mahindra AMC",
        "nav": 134.56,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_NIFTY_50_INDEX_0073": {
        "asset_code": "ASSET_AXIS_NIFTY_50_INDEX_0073",
        "scheme_name": "Axis Mutual Fund Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "Axis Mutual Fund",
        "nav": 136.29,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_NIFTY_NEXT_50_0074": {
        "asset_code": "ASSET_AXIS_NIFTY_NEXT_50_0074",
        "scheme_name": "Axis Mutual Fund Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "Axis Mutual Fund",
        "nav": 138.02,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_MIDCAP_OPPORTUNITIES_0075": {
        "asset_code": "ASSET_AXIS_MIDCAP_OPPORTUNITIES_0075",
        "scheme_name": "Axis Mutual Fund Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "Axis Mutual Fund",
        "nav": 139.75,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_SMALL_CAP_DISCOVERY_0076": {
        "asset_code": "ASSET_AXIS_SMALL_CAP_DISCOVERY_0076",
        "scheme_name": "Axis Mutual Fund Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "Axis Mutual Fund",
        "nav": 141.48,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_FOCUSED_EQUITY_30_0077": {
        "asset_code": "ASSET_AXIS_FOCUSED_EQUITY_30_0077",
        "scheme_name": "Axis Mutual Fund Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "Axis Mutual Fund",
        "nav": 143.21,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_HEALTHCARE_PHARMA_ETF_0078": {
        "asset_code": "ASSET_AXIS_HEALTHCARE_PHARMA_ETF_0078",
        "scheme_name": "Axis Mutual Fund Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "Axis Mutual Fund",
        "nav": 144.94,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_TECHNOLOGY_AI_ETF_0079": {
        "asset_code": "ASSET_AXIS_TECHNOLOGY_AI_ETF_0079",
        "scheme_name": "Axis Mutual Fund Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "Axis Mutual Fund",
        "nav": 146.67,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_BANKING_FINANCIAL_ETF_0080": {
        "asset_code": "ASSET_AXIS_BANKING_FINANCIAL_ETF_0080",
        "scheme_name": "Axis Mutual Fund Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "Axis Mutual Fund",
        "nav": 148.4,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_CORPORATE_BOND_AAA_0081": {
        "asset_code": "ASSET_AXIS_CORPORATE_BOND_AAA_0081",
        "scheme_name": "Axis Mutual Fund Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "Axis Mutual Fund",
        "nav": 150.13,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_SHORT_TERM_DEBT_FUND_0082": {
        "asset_code": "ASSET_AXIS_SHORT_TERM_DEBT_FUND_0082",
        "scheme_name": "Axis Mutual Fund Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "Axis Mutual Fund",
        "nav": 151.86,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_OVERNIGHT_LIQUID_FUND_0083": {
        "asset_code": "ASSET_AXIS_OVERNIGHT_LIQUID_FUND_0083",
        "scheme_name": "Axis Mutual Fund Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "Axis Mutual Fund",
        "nav": 153.59,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_AXIS_SOVEREIGN_GOLD_BOND_0084": {
        "asset_code": "ASSET_AXIS_SOVEREIGN_GOLD_BOND_0084",
        "scheme_name": "Axis Mutual Fund Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "Axis Mutual Fund",
        "nav": 155.32,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_NIFTY_50_INDEX_0085": {
        "asset_code": "ASSET_MIRA_NIFTY_50_INDEX_0085",
        "scheme_name": "Mirae Asset Mutual Fund Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 157.05,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_NIFTY_NEXT_50_0086": {
        "asset_code": "ASSET_MIRA_NIFTY_NEXT_50_0086",
        "scheme_name": "Mirae Asset Mutual Fund Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 158.78,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_MIDCAP_OPPORTUNITIES_0087": {
        "asset_code": "ASSET_MIRA_MIDCAP_OPPORTUNITIES_0087",
        "scheme_name": "Mirae Asset Mutual Fund Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 160.51,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_SMALL_CAP_DISCOVERY_0088": {
        "asset_code": "ASSET_MIRA_SMALL_CAP_DISCOVERY_0088",
        "scheme_name": "Mirae Asset Mutual Fund Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 162.24,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_FOCUSED_EQUITY_30_0089": {
        "asset_code": "ASSET_MIRA_FOCUSED_EQUITY_30_0089",
        "scheme_name": "Mirae Asset Mutual Fund Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 163.97,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_HEALTHCARE_PHARMA_ETF_0090": {
        "asset_code": "ASSET_MIRA_HEALTHCARE_PHARMA_ETF_0090",
        "scheme_name": "Mirae Asset Mutual Fund Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 165.7,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_TECHNOLOGY_AI_ETF_0091": {
        "asset_code": "ASSET_MIRA_TECHNOLOGY_AI_ETF_0091",
        "scheme_name": "Mirae Asset Mutual Fund Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 167.43,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_BANKING_FINANCIAL_ETF_0092": {
        "asset_code": "ASSET_MIRA_BANKING_FINANCIAL_ETF_0092",
        "scheme_name": "Mirae Asset Mutual Fund Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 169.16,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_CORPORATE_BOND_AAA_0093": {
        "asset_code": "ASSET_MIRA_CORPORATE_BOND_AAA_0093",
        "scheme_name": "Mirae Asset Mutual Fund Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 170.89,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_SHORT_TERM_DEBT_FUND_0094": {
        "asset_code": "ASSET_MIRA_SHORT_TERM_DEBT_FUND_0094",
        "scheme_name": "Mirae Asset Mutual Fund Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 172.62,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_OVERNIGHT_LIQUID_FUND_0095": {
        "asset_code": "ASSET_MIRA_OVERNIGHT_LIQUID_FUND_0095",
        "scheme_name": "Mirae Asset Mutual Fund Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 174.35,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_MIRA_SOVEREIGN_GOLD_BOND_0096": {
        "asset_code": "ASSET_MIRA_SOVEREIGN_GOLD_BOND_0096",
        "scheme_name": "Mirae Asset Mutual Fund Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "Mirae Asset Mutual Fund",
        "nav": 176.08,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _NIFTY_50_INDEX_0097": {
        "asset_code": "ASSET_UTI _NIFTY_50_INDEX_0097",
        "scheme_name": "UTI Mutual Fund Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "UTI Mutual Fund",
        "nav": 177.81,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _NIFTY_NEXT_50_0098": {
        "asset_code": "ASSET_UTI _NIFTY_NEXT_50_0098",
        "scheme_name": "UTI Mutual Fund Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "UTI Mutual Fund",
        "nav": 179.54,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _MIDCAP_OPPORTUNITIES_0099": {
        "asset_code": "ASSET_UTI _MIDCAP_OPPORTUNITIES_0099",
        "scheme_name": "UTI Mutual Fund Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "UTI Mutual Fund",
        "nav": 181.27,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _SMALL_CAP_DISCOVERY_0100": {
        "asset_code": "ASSET_UTI _SMALL_CAP_DISCOVERY_0100",
        "scheme_name": "UTI Mutual Fund Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "UTI Mutual Fund",
        "nav": 183.0,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _FOCUSED_EQUITY_30_0101": {
        "asset_code": "ASSET_UTI _FOCUSED_EQUITY_30_0101",
        "scheme_name": "UTI Mutual Fund Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "UTI Mutual Fund",
        "nav": 184.73,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _HEALTHCARE_PHARMA_ETF_0102": {
        "asset_code": "ASSET_UTI _HEALTHCARE_PHARMA_ETF_0102",
        "scheme_name": "UTI Mutual Fund Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "UTI Mutual Fund",
        "nav": 186.46,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _TECHNOLOGY_AI_ETF_0103": {
        "asset_code": "ASSET_UTI _TECHNOLOGY_AI_ETF_0103",
        "scheme_name": "UTI Mutual Fund Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "UTI Mutual Fund",
        "nav": 188.19,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _BANKING_FINANCIAL_ETF_0104": {
        "asset_code": "ASSET_UTI _BANKING_FINANCIAL_ETF_0104",
        "scheme_name": "UTI Mutual Fund Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "UTI Mutual Fund",
        "nav": 189.92,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _CORPORATE_BOND_AAA_0105": {
        "asset_code": "ASSET_UTI _CORPORATE_BOND_AAA_0105",
        "scheme_name": "UTI Mutual Fund Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "UTI Mutual Fund",
        "nav": 191.65,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _SHORT_TERM_DEBT_FUND_0106": {
        "asset_code": "ASSET_UTI _SHORT_TERM_DEBT_FUND_0106",
        "scheme_name": "UTI Mutual Fund Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "UTI Mutual Fund",
        "nav": 193.38,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _OVERNIGHT_LIQUID_FUND_0107": {
        "asset_code": "ASSET_UTI _OVERNIGHT_LIQUID_FUND_0107",
        "scheme_name": "UTI Mutual Fund Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "UTI Mutual Fund",
        "nav": 195.11,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_UTI _SOVEREIGN_GOLD_BOND_0108": {
        "asset_code": "ASSET_UTI _SOVEREIGN_GOLD_BOND_0108",
        "scheme_name": "UTI Mutual Fund Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "UTI Mutual Fund",
        "nav": 196.84,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _NIFTY_50_INDEX_0109": {
        "asset_code": "ASSET_DSP _NIFTY_50_INDEX_0109",
        "scheme_name": "DSP Mutual Fund Large Cap Index Direct Growth",
        "category": "NIFTY_50_INDEX",
        "fund_manager": "DSP Mutual Fund",
        "nav": 198.57,
        "cagr_3y": 14.8,
        "risk_rating": "LOW_TO_MODERATE",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _NIFTY_NEXT_50_0110": {
        "asset_code": "ASSET_DSP _NIFTY_NEXT_50_0110",
        "scheme_name": "DSP Mutual Fund Large & Mid Cap Direct Growth",
        "category": "NIFTY_NEXT_50",
        "fund_manager": "DSP Mutual Fund",
        "nav": 200.3,
        "cagr_3y": 16.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0035,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _MIDCAP_OPPORTUNITIES_0111": {
        "asset_code": "ASSET_DSP _MIDCAP_OPPORTUNITIES_0111",
        "scheme_name": "DSP Mutual Fund Mid Cap Growth Direct Growth",
        "category": "MIDCAP_OPPORTUNITIES",
        "fund_manager": "DSP Mutual Fund",
        "nav": 202.03,
        "cagr_3y": 19.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0065,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _SMALL_CAP_DISCOVERY_0112": {
        "asset_code": "ASSET_DSP _SMALL_CAP_DISCOVERY_0112",
        "scheme_name": "DSP Mutual Fund Small Cap Alpha Direct Growth",
        "category": "SMALL_CAP_DISCOVERY",
        "fund_manager": "DSP Mutual Fund",
        "nav": 203.76,
        "cagr_3y": 22.4,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.0075,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _FOCUSED_EQUITY_30_0113": {
        "asset_code": "ASSET_DSP _FOCUSED_EQUITY_30_0113",
        "scheme_name": "DSP Mutual Fund Multi Cap Focused Direct Growth",
        "category": "FOCUSED_EQUITY_30",
        "fund_manager": "DSP Mutual Fund",
        "nav": 205.49,
        "cagr_3y": 15.6,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.006,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _HEALTHCARE_PHARMA_ETF_0114": {
        "asset_code": "ASSET_DSP _HEALTHCARE_PHARMA_ETF_0114",
        "scheme_name": "DSP Mutual Fund Sectoral Healthcare Direct Growth",
        "category": "HEALTHCARE_PHARMA_ETF",
        "fund_manager": "DSP Mutual Fund",
        "nav": 207.22,
        "cagr_3y": 17.1,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.0045,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _TECHNOLOGY_AI_ETF_0115": {
        "asset_code": "ASSET_DSP _TECHNOLOGY_AI_ETF_0115",
        "scheme_name": "DSP Mutual Fund Sectoral Technology Direct Growth",
        "category": "TECHNOLOGY_AI_ETF",
        "fund_manager": "DSP Mutual Fund",
        "nav": 208.95,
        "cagr_3y": 24.8,
        "risk_rating": "VERY_HIGH",
        "total_expense_ratio": 0.005,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _BANKING_FINANCIAL_ETF_0116": {
        "asset_code": "ASSET_DSP _BANKING_FINANCIAL_ETF_0116",
        "scheme_name": "DSP Mutual Fund Sectoral Banking Direct Growth",
        "category": "BANKING_FINANCIAL_ETF",
        "fund_manager": "DSP Mutual Fund",
        "nav": 210.68,
        "cagr_3y": 15.2,
        "risk_rating": "HIGH",
        "total_expense_ratio": 0.004,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _CORPORATE_BOND_AAA_0117": {
        "asset_code": "ASSET_DSP _CORPORATE_BOND_AAA_0117",
        "scheme_name": "DSP Mutual Fund Corporate Debt Direct Growth",
        "category": "CORPORATE_BOND_AAA",
        "fund_manager": "DSP Mutual Fund",
        "nav": 212.41,
        "cagr_3y": 7.8,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.0025,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _SHORT_TERM_DEBT_FUND_0118": {
        "asset_code": "ASSET_DSP _SHORT_TERM_DEBT_FUND_0118",
        "scheme_name": "DSP Mutual Fund Short Duration Debt Direct Growth",
        "category": "SHORT_TERM_DEBT_FUND",
        "fund_manager": "DSP Mutual Fund",
        "nav": 214.14,
        "cagr_3y": 7.2,
        "risk_rating": "LOW",
        "total_expense_ratio": 0.002,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _OVERNIGHT_LIQUID_FUND_0119": {
        "asset_code": "ASSET_DSP _OVERNIGHT_LIQUID_FUND_0119",
        "scheme_name": "DSP Mutual Fund Liquid Cash Reserve Direct Growth",
        "category": "OVERNIGHT_LIQUID_FUND",
        "fund_manager": "DSP Mutual Fund",
        "nav": 215.87,
        "cagr_3y": 6.8,
        "risk_rating": "VERY_LOW",
        "total_expense_ratio": 0.001,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
    "ASSET_DSP _SOVEREIGN_GOLD_BOND_0120": {
        "asset_code": "ASSET_DSP _SOVEREIGN_GOLD_BOND_0120",
        "scheme_name": "DSP Mutual Fund Gold Vault Security Direct Growth",
        "category": "SOVEREIGN_GOLD_BOND",
        "fund_manager": "DSP Mutual Fund",
        "nav": 217.6,
        "cagr_3y": 12.5,
        "risk_rating": "MODERATE",
        "total_expense_ratio": 0.0,
        "min_sip_amount": 500.0,
        "min_lumpsum_amount": 1000.0,
    },
}
